### PR TITLE
Fix Canvas#legal_viewing_hint_values.

### PR DESCRIPTION
**Pull request by tpendragon**

### CODE REVIEW

**Comment by azaroth42** [comment]
:-1: to the test. Viewing hints can be anything, we only define some of them.

See: http://iiif.io/api/presentation/2.0/#technical-properties

**Comment by jpstroop** [comment]
That's why you can serialize w/ `force: true`.

**Comment by tpendragon** [comment]
@azaroth42 I changed the test, but that argument makes the case for "don't validate using a whitelist of values," when for the moment I just want it to not error.

**Comment by azaroth42** [comment]
:+1: to unknown viewingHints being not an error. Can you warn and continue instead of failing?

**Comment by azaroth42** [comment]
For example: https://github.com/IIIF/presentation-api/blob/master/implementations/manifest-factory/factory.py#L569

**Comment by jpstroop** [comment]
You could, but again, that's what `force: true` is for. As there's no logging apparatus in osullivan (so you fail or don't; there's nowhere to send a warning), it would be up to the upstream application to handle the error (and continue or fail as appropriate) when passing an unspecified value.

**Comment by jpstroop** [comment]
I'd be much more worried about someone setting it to `nonPaged` instead of `non-paged`.

**Pull request merged**
